#!/usr/bin/env python3
"""Generate build/overlay_pages.h from the actual overlay .bin sizes.

The overlay library spans TWO 8KB flash sets (the fire-24-e has no 16KB chip,
and a SLOT_PEEK across two chips of one set isn't contiguous -- see
docs/RBCP-DESIGN.md). Each set holds whole overlays packed from page 0; no
overlay may straddle a set, so a fetch's SLOT_PEEK always stays within one 8KB
chip (the proven case). For each overlay this emits its first page WITHIN its
set and the loadable set index, so the resident thunks never hardcode either.

To rebalance, edit LAYOUT below (and the matching concatenation in the
Makefile's overlays_a/b.bin rules). Loadable set indices: shell=0, stock=1,
overlays-A=2, overlays-B=3 (cfg/onerom-stock.json order; plugins don't count).

Usage: gen_overlay_pages.py <build-dir>   (writes the header to stdout)
"""
import os
import sys

build = sys.argv[1]
ovl = os.path.join(build, "overlays")

# (bin, MACRO, "PAGE"|"FIRST_PAGE", flash_set). Overlays sharing a set pack
# consecutively from page 0; each set is one 8KB chip = 32 pages.
LAYOUT = [
    ("files.bin", "FILES", "FIRST_PAGE", 2),
    ("dir.bin",   "DIR",   "FIRST_PAGE", 2),
    ("edit.bin",  "EDIT",  "FIRST_PAGE", 3),
    ("about.bin", "ABOUT", "FIRST_PAGE", 3),
    ("picker.bin", "PICKER", "FIRST_PAGE", 3),
]


def pages(name):
    return (os.path.getsize(os.path.join(ovl, name)) + 255) // 256


lines = []
notes = []
next_page = {}          # flash_set -> next free page within that set
for binname, macro, suffix, fset in LAYOUT:
    p = next_page.get(fset, 0)
    n = pages(binname)
    if p + n > 32:
        sys.exit("gen_overlay_pages: %s (%d pages) overflows 8KB flash set %d "
                 "at page %d" % (binname, n, fset, p))
    next_page[fset] = p + n
    lines.append("#define %s_%s %d" % (macro, suffix, p))
    lines.append("#define %s_SET %d" % (macro, fset))
    notes.append("%s@set%d:p%d(+%d)" % (macro.lower(), fset, p, n))

sys.stdout.write(
    "/* generated by tools/gen_overlay_pages.py -- per-overlay first page and\n"
    "   flash set. Do not edit; rebuilt from the overlay .bin sizes. */\n"
    "#ifndef OVERLAY_PAGES_H\n"
    "#define OVERLAY_PAGES_H\n"
    + "\n".join(lines) + "\n"
    "#endif\n"
)
sys.stderr.write("  overlay_pages.h: " + " ".join(notes) + "\n")
