#!/usr/bin/env python3
"""Generate build/overlay_pages.h from the actual overlay .bin sizes.

The overlays are concatenated into overlays.bin in this order: about, files,
edit. Each starts at a 256-byte page boundary (the .bin are padded to a page
multiple), so an overlay's start page is the running page total of everything
before it. The resident thunks include this header instead of hardcoding the
numbers, so a size change in one overlay can't silently misnumber a later one.

Usage: gen_overlay_pages.py <build-dir>   (writes the header to stdout)
"""
import os
import sys

build = sys.argv[1]
ovl = os.path.join(build, "overlays")


def pages(name):
    return (os.path.getsize(os.path.join(ovl, name)) + 255) // 256


about_pages = pages("about.bin")            # about occupies [0, about_pages)
files_first = about_pages
dir_first = files_first + pages("files.bin")
edit_first = dir_first + pages("dir.bin")

sys.stdout.write(
    "/* generated by tools/gen_overlay_pages.py -- overlay start pages.\n"
    "   Do not edit; rebuilt from the overlay .bin sizes. */\n"
    "#ifndef OVERLAY_PAGES_H\n"
    "#define OVERLAY_PAGES_H\n"
    "#define ABOUT_PAGE 0\n"
    "#define FILES_FIRST_PAGE %d\n"
    "#define DIR_FIRST_PAGE %d\n"
    "#define EDIT_FIRST_PAGE %d\n"
    "#endif\n" % (files_first, dir_first, edit_first)
)
sys.stderr.write("  overlay_pages.h: files@%d dir@%d edit@%d\n"
                 % (files_first, dir_first, edit_first))
